services:
  nginx:
    image: nginx:alpine
    container_name: finance-tracker-nginx
    working_dir: /var/www/finance-api
    volumes:
      - ./:/var/www/finance-api
      - ./docker/nginx/finance-tracker-local.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
      - postgres
    depends_on:
      - php
      - postgres
    ports:
      - "8028:80"

  redis:
    container_name: finance-tracker-redis
    build: ./docker/redis
    volumes:
      - redis_finance-tracker:/data
    ports:
      - "6358:6379"

  php:
    container_name: finance-tracker-php
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/finance-api
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/z-php.ini
    working_dir: /var/www/finance-api
    depends_on:
      - redis
      - postgres
    links:
      - redis
      - postgres
    ports:
      - "9079:9000"

  postgres:
    container_name: finance-tracker-postgres
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: finance-tracker
      POSTGRES_USER: finance-user
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres_finance-tracker:/data/postgres
    ports:
      - "5483:5432"

volumes:
  postgres_finance-tracker:
    driver: local
  redis_finance-tracker:
    driver: local
